### PR TITLE
Added gradient-curve sif test-files

### PR DESCRIPTION
**Pull request by ankit-kumar-dwivedi**
"Closes: #3"
added following files...
```
gradient-curve-shape1-width-0.25.sif
gradient-curve-shape1-width-0.sif
gradient-curve-shape1-width-1.sif
gradient-curve-shape1-width-10.sif
gradient-curve-shape1-width-25-loop.sif
gradient-curve-shape1-width-25-nofast.sif
gradient-curve-shape1-width-25-perpendicular.sif
gradient-curve-shape1-width-25-zigzag.sif
gradient-curve-shape1-width-25.sif
gradient-curve-shape1-width-250.sif
gradient-curve-shape1-width-60.sif
...
...
------ same for all 7 shapes
```

### CODE REVIEW

**Comment by morevnaproject** [comment]
I have checked all files, good work!

Can you please ad also:
- gradient-curve-shape*-width-25-loop-zigzag.sif
- gradient-curve-shape*-width-60-loop.sif
- gradient-curve-shape*-width-60-loop-zigzag.sif
- gradient-curve-shape*-width-60-zigzag.sif

Thank you!

**Comment by ankit-kumar-dwivedi** [comment]
https://youtu.be/QhCUdk91_EY
I had some fun :p

**Comment by ankit-kumar-dwivedi** [comment]
okay just 5 minutes

**Comment by morevnaproject** [comment]
Great! Thank you for the contribution!

**Pull request merged**
