### PR TITLE
added test files for gradient-radial

### PR DESCRIPTION
**Pull request by ankit-kumar-dwivedi**
"Closes: #8 "
Added all 10 .sif files
**I used the standard HTML color codes.**
Changes to the following file hierarchy
```
sources
└─── layers
          └───gradient-curve
```
is now 
```
sources
└─── layers
          └───gradient
                   └───gradient-curve
                   └───gradient-radial
```

### CODE REVIEW

**Comment by reSHARMA** [comment]
Thanks! The change in directory structure looks good to me!

**Comment by ankit-kumar-dwivedi** [comment]
@reSHARMA Kindly merge this PR so I can more PRs :)

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Still, I would like to keep an old directory structure. (Too much of word "gradient" for my taste). Can you please fix the structure back? ^__^

**Comment by morevnaproject** [comment]
@ankit-kumar-dwivedi Also, I can see this PR includes files for "gradient-conical". Can you please submit them as separate PR? (Otherwise you will get less points - leaderboard assigns points for each PR).

**Comment by morevnaproject** [comment]
Quick review of he PR:
* "gradient-radial-black-white-loop.sif" - I can see this file contains one extra layer (with red color). Please remove it.
* "gradient-radial-black-white-zigzag.sif" - Same here - extra layer.
* "gradient-radial-black-white-zigzag.sif" - Same here - extra layer.

**Comment by ankit-kumar-dwivedi** [comment]
> 
> 
> Quick review of he PR:
> 
>     * "gradient-radial-black-white-loop.sif" - I can see this file contains one extra layer (with red color). Please remove it.
> 
>     * "gradient-radial-black-white-zigzag.sif" - Same here - extra layer.
> 
>     * "gradient-radial-black-white-zigzag.sif" - Same here - extra layer.

okay will do that in few mins : )

**Comment by ankit-kumar-dwivedi** [comment]
Done with that @morevnaproject anything else?

**Comment by morevnaproject** [comment]
Looks good now. Thank you for your contribution!

**Pull request merged**
