### PR TITLE
Added the fetch-icon bash script

### PR DESCRIPTION
**Pull request by ankit-kumar-dwivedi**
Closes: #10 
@morevnaproject 
please have a look at the script file and let me know if any changes are required

### CODE REVIEW

**Comment by morevnaproject** [comment]
Hello! For some reason I can see too many modified file in this pull request? Possibly, this is a CR/LF issue (compatibility of Linux/Windows line endings). Can you please revert commit aba84789bbf25a2be31c107a88d537b9dfa8e129 and then commit a single "fetch-icon.sh" file?

I tried to run the script, but got those errors:
```
konstantin@master:~/sources/synfig-tests-regressions$ LANG=C ./fetch-icons.sh 
A    /tmp/images/CMakeLists.txt
A    /tmp/images/Makefile.am
A    /tmp/images/Makefile.inc
...
A    /tmp/images/wallpaper.sif
Checked out revision 9938.
'about_icon.sif' -> '/home/konstantin/sources/synfig-tests-regressions/sources/icons/'
cp: cannot create regular file '/home/konstantin/sources/synfig-tests-regressions/sources/icons/': Not a directory
'action_add_to_set_icon.sif' -> '/home/konstantin/sources/synfig-tests-regressions/sources/icons/'
cp: cannot create regular file '/home/konstantin/sources/synfig-tests-regressions/sources/icons/': Not a directory
'action_doc_icons.sif' -> '/home/konstantin/sources/synfig-tests-regressions/sources/icons/'
cp: cannot create regular file '/home/konstantin/sources/synfig-tests-regressions/sources/icons/': Not a directory
'action_export_icon.sif' -> '/home/konstantin/sources/synfig-tests-regressions/sources/icons/'
cp: cannot create regular file '/home/konstantin/sources/synfig-tests-regressions/sources/icons/': Not a directory
'action_flat_interpolation_icon.sif' -> '/home/konstantin/sources/synfig-tests-regressions/sources/icons/'
cp: cannot create regular file '/home/konstantin/sources/synfig-tests-regressions/sources/icons/': Not a directory
'action_interpolate_interpolation_icon.sif' -> '/home/konstantin/sources/synfig-tests-regressions/sources/icons/'
...
```

**Comment by ankit-kumar-dwivedi** [comment]
hey, @morevnaproject I assumed "icons" is created however Will handle this with some code.
Can you tell me how not to get the CRLF issue as I switched from windows to Linux? I tried googling it but was unable to get a satisfactory answer.
thanks in advance!

**Comment by morevnaproject** [comment]
> Can you tell me how not to get the CRLF issue as I switched from windows to Linux?

Sure! Please let me know one thing - did you copied your "synfig-tests-regressions" from Windows machine or did you cloned it "from scratch" into Linux?

**Comment by ankit-kumar-dwivedi** [comment]
> 
> 
> > Can you tell me how not to get the CRLF issue as I switched from windows to Linux?
> 
> Sure! Please let me know one thing - did you copied your "synfig-tests-regressions" from Windows machine or did you cloned it "from scratch" into Linux?

I'm using same machine and same code 
So no I didn't cloned it

**Comment by morevnaproject** [comment]
Please cd into repository dir and execute this command:
```git config core.autocrlf```

Does it outputs anything?

**Comment by ankit-kumar-dwivedi** [comment]
>  `git config core.autocrlf`

No Ouput :worried:

**Pull request closed without merging**
